import{a as p,i as g}from"./assets/vendor-a287c628.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerpolicy&&(n.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?n.credentials="include":t.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();p.defaults.headers.common["x-api-key"]="live_8dopgEoZqjLeDX5BcU4nL2k4qRgKONIXj7FAVN0qokHbLiZxLlebiy9Al26Wgzgs";function y(){return p.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data).catch(e=>{throw console.error("Error fetching breeds:",e),e})}function b(e){return p.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(r=>r.data).catch(r=>{throw console.error("Error fetching cat by breed:",r),r})}const c=document.querySelector(".breed-select"),m=document.querySelector(".cat-info"),h=document.querySelector(".loader");document.querySelector(".error");g.success({title:"Success",message:"Operation completed successfully"});function f(){h.classList.add("visible"),c.classList.add("hidden"),m.classList.add("hidden")}function L(){c.classList.add("hidden")}function l(){h.classList.remove("visible")}function v(){c.classList.remove("hidden")}function E(e){c.innerHTML="",e.forEach(r=>{const s=document.createElement("option");s.value=r.id,s.textContent=r.name,c.appendChild(s)})}function $(e,r,s,a){const t=document.createElement("img");t.src=e[0].url,t.alt=`${e[0].breeds[0].name}`;const n=document.createElement("p");n.textContent=`Breed: ${e[0].breeds[0].name}`;const i=document.createElement("p");i.textContent=`Description: ${e[0].breeds[0].description}`;const u=document.createElement("p");u.textContent=`Temperament: ${e[0].breeds[0].temperament}`;const o=document.createElement("img");o.src=`https://flagsapi.com/${s}/shiny/64.png`,o.alt=`${r}`,o.onerror=()=>{o.src=a},o.style.width="64px";const d=document.createElement("div");d.classList.add("wrapper"),d.innerHTML=`
    <img class="cat-img" width="400" src="${t.src}" alt="${t.alt}">
    <div class="info-wrap">
      <h2 class="info-title">${n.textContent}</h2>
      <p><b class="primary">Description:</b> ${i.textContent}</p>
      <p><b class="primary">Temperament:</b> ${u.textContent}</p>
      <div>
        <p><b class="primary">Country:</b> ${r}</p>
        <img class="cat-img" width="400" src="${o.src}" alt="${o.alt}">
      </div>
    </div>
  `,d.appendChild(o),m.innerHTML="",m.appendChild(d)}f();y().then(e=>{l(),E(e),v()}).catch(()=>{l(),showError()});c.addEventListener("change",()=>{const e=c.value;e&&(f(),hideError(),L(),b(e).then(r=>{l(),$(r)}).catch(()=>{l(),showError()}))});
//# sourceMappingURL=commonHelpers.js.map
